version: 0.1

phases:
  build:
    commands:
      - echo Nothing to do yet
artifacts:
  files:
    - index.html
    - favicon.ico
    - sajan-raj-ojha-resume.pdf
    
    - css/*
    - img/*
    - js/*
